services:
  sensevoice:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/sensevoice:v2025.4.13-action
    container_name: sensevoice
    hostname: sensevoice
    environment:
      - TZ=Asia/Shanghai
      # - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./:/app/sensevoice
    ports:
      - "50000:50000"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - sensevoice

networks:
  sensevoice:
    driver: bridge
    name: sensevoice
