services:
  sensevoice:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/sensevoice
    container_name: sensevoice
    hostname: sensevoice
    environment:
      - TZ=Asia/Shanghai
      - HF_HOME=/app
      - MODELSCOPE_CACHE=/app
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - share=True
      # - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./:/app/sensevoice
      - ./models:/app/models
      - ./models:/app/modelscope
    ports:
      - "8000:8000"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - sensevoice
    entrypoint: ["python", "webui.py", "--listen"]

networks:
  sensevoice:
    driver: bridge
    name: sensevoice
