services:
  sensevoice:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/sensevoice:v2025.04.13-action
    container_name: sensevoice
    hostname: sensevoice
    environment:
      - TZ=Asia/Shanghai
      - HF_HOME=/app
      - MODELSCOPE_CACHE=/app
      # - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./:/app/sensevoice
      - O:\Hub\modelscope\hub\models:/app/models
      - O:\Hub\huggingface:/app/huggingface
      - O:\Hub\modelscope:/app/modelscope
    ports:
      - "7860:7860"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - sensevoice

networks:
  sensevoice:
    driver: bridge
    name: sensevoice
